# Generated by Django 4.1.5 on 2023-01-31 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_bookingmodel_id_alter_eventmodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='u_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
