# Generated by Django 4.1.5 on 2023-01-31 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_bookingmodel_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Events.eventmodel'),
        ),
    ]
